[metadata]
name = Faaiduck
version = 0.1.4
description = Cantonese stenography system for Plover
long_description = file: README.md
long_description_content_type = text/markdown
author = Chaak Lau
license = Proprietary
url = https://github.com/chaaklau/Faaiduck
project_urls =
    Source Code = https://github.com/chaaklau/Faaiduck
keywords = plover plover_plugin cantonese steno stenography

[options]
zip_safe = False
install_requires =
    plover>=5.2.3
    plover-python-dictionary
packages =
    Faaiduck
    Faaiduck.dictionaries
    Faaiduck.dictionaries.default

[options.entry_points]
plover.system =
    Faaiduck = Faaiduck.system

[options.package_data]
Faaiduck.dictionaries.default =
    *.csv
    *.json
    *.py
